### PR TITLE
Fix template & Round to integer

### PR DESCRIPTION
**Pull request by DHdroid**
[논의내용](https://www.notion.so/minchan0502/28f094cd4c6743a3b19b5894d7c56699?pvs=4#737e9366058c4af1a69c7d1e11934f7c) 를 반영하는 pr

### CODE REVIEW

**Comment by DHdroid** [comment]
참고)
image

**Comment by DHdroid** [comment]
참고)
image

**Review by nemodleo — APPROVED** [review]
good

**Review by yoonichoi — COMMENTED** [review]
lgtm

**Pull request merged**
